//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_1._0_
{
    using System;
    using System.Collections.Generic;
    
    public partial class sachmua
    {
        public int masach { get; set; }
        public Nullable<System.DateTime> ngaymua { get; set; }
        public Nullable<int> madocgia { get; set; }
    
        public virtual docgia docgia { get; set; }
        public virtual sach sach { get; set; }
    }
}
